import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'getting-started/index',
    {
      type: 'category',
      label: 'Packages',
      items: [
        {
          type: 'category',
          label: 'MCP Gearbox CLI',
          items: [
            'packages/mcp-gearbox-cli/index',
            'packages/mcp-gearbox-cli/usage',
            'packages/mcp-gearbox-cli/copilot',
            'packages/mcp-gearbox-cli/copilot-cli',
            'packages/mcp-gearbox-cli/continue',
            'packages/mcp-gearbox-cli/kiro',
            'packages/mcp-gearbox-cli/cursor',
            'packages/mcp-gearbox-cli/claude',
            'packages/mcp-gearbox-cli/gemini',
            'packages/mcp-gearbox-cli/qoder',
            'packages/mcp-gearbox-cli/lmstudio',
            'packages/mcp-gearbox-cli/development',
          ],
        },
        {
          type: 'category',
          label: 'MCP Gearbox Desktop',
          items: [
            'packages/mcp-gearbox/index',
            'packages/mcp-gearbox/installation',
            'packages/mcp-gearbox/usage',
          ],
        },
        {
          type: 'category',
          label: 'MCP Gearbox JS',
          items: [
            'packages/mcp-gearbox-js/index',
            'packages/mcp-gearbox-js/usage',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/tool-comparison',
        'guides/working-with-servers',
      ],
    },
  ],
};

export default sidebars;